copyright: Copyright &copy; 2016

site_name: msm-lite
site_url: http://www.mkdocs.org
site_author: Krzysztof Jusiak
repo_url: https://github.com/krzysztof-jusiak/msm-lite
repo_name: msm-lite
use_directory_urls: false
theme_dir: readthedocs
extra_javascript: [js/gitter.js, js/cpp.js, js/html.js, js/youtube.js, js/codemirror/codemirror.js, js/codemirror/active-line.js, js/codemirror/clike.js]
extra_css: [css/codemirror.css, css/mdn-like.css]

docs_dir: .
pages:
- Home: index.md
- Overview: overview.md
- User Guide: user_guide.md
- Reference: reference.md
- Examples: examples.md
- CHANGELOG: CHANGELOG.md
- TODO: TODO.md
