copyright: Copyright &copy; 2016-2017

site_name: "[Boost].SML"
site_url: http://boost-experimental.github.io/sml
site_author: Kris Jusiak
repo_url: https://github.com/boost-experimental/sml
repo_name: sml
docs_dir: .
use_directory_urls: false
theme_dir: themes/boost-experimental
google_analytics: ['UA-73083568-1', 'auto']
extra_javascript: []
extra_css: []

pages:
- Introduction: index.md
- Overview: overview.md
- Features/Benchmarks: benchmarks.md
- Tutorial/Workshop: tutorial.md
- UML vs SML: uml_vs_sml.md
- User Guide: user_guide.md
- Examples: examples.md
- FAQ: faq.md
- CHANGELOG: CHANGELOG.md
